### PR TITLE
Roughout of Sphinx Docs

### PR DESCRIPTION
**Pull request by norlandrhagen**
Start to address https://github.com/TomNicholas/VirtualiZarr/issues/8

To Do:
- [] Publish on RTD

cc @TomNicholas

### CODE REVIEW

**Comment by norlandrhagen** [comment]
Updated to include start of API docs:

https://github.com/TomNicholas/VirtualiZarr/issues/24

**Comment by TomNicholas** [comment]
Amazing! Thank you for helping with this @norlandrhagen ! Let me know when I should merge it

**Comment by norlandrhagen** [comment]
Np! There are a few outstanding nits. 

A few questions for you @TomNicholas .
- Do you have a RTD account you would like this under?
- Do you want to keep this theme or switch?

I can polish up the last few bits and we can get it merged.

**Comment by TomNicholas** [comment]
> Do you have a RTD account you would like this under?

I do - under my github account. What do I need to do to add it?

> Do you want to keep this theme or switch?


I don't have strong feelings on the theme, but I'm hoping this project will get moved into the zarr-developers orgs, so it might be nice to match whatever theme was used for the [zarr-python](https://github.com/zarr-developers/zarr-python) docs?

**Pull request merged**
